x-common-service: &common-service
  build:
    context: ./backend
    dockerfile: ./build/Dockerfile
    args:
      BUILD_ENV: "dev"
  image: theater/backend
  env_file:
    - ./backend/.env.dev
  volumes:
    - ./backend:/opt/theater/backend
  depends_on:
    theater_db:
      condition: service_healthy

services:
  theater_api:
    <<: *common-service
    container_name: theater_api
    command:
      - --reload
    ports:
      - "8015:5000"
    healthcheck:
      test: ["CMD", "curl", "-f", "localhost:5000/api/v1/healthcheck/"]
      interval: 30s
      timeout: 5s
      retries: 5

  theater_migration:
    <<: *common-service
    container_name: theater_migration
    command:
      - migration

  theater_db:
    image: postgres:15.3-alpine
    container_name: theater_db
    volumes:
      - ./.docker/pg_data:/var/lib/postgresql/data
    env_file:
      - ./backend/.env.dev
    expose:
      - 5432
    ports:
      - "5437:5432"
    healthcheck:
      test: [ "CMD-SHELL", "sh -c 'pg_isready -U docker -d theater_db'" ]
      start_period: 5s
      interval: 5s
      timeout: 5s
      retries: 50
